apiVersion: v1
kind: Secret
metadata:
    name: stripe-secret
type: Opaque
data:
    STRIPE_KEY: dXNlcm5hbWU=
---
apiVersion: v1
kind: Secret
metadata:
    name: jwt-secret
type: Opaque
data:
    JWT_KEY: dXNlcm5hbWU=
