apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: volantebjb/ticketix-client
        # imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: client-svc
spec:
  # type: NodePort
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      # nodePort: 30100
